version: '3.7'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /usr/src/tourist_app_drf/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/tourist_app_drf
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./.env
volumes:
  postgres_data:

